//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntityTest.Data1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShirenEntities : DbContext
    {
        public ShirenEntities()
            : base("name=ShirenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Poem> Poem { get; set; }
        public virtual DbSet<Poet> Poet { get; set; }
        public virtual DbSet<Meter> Meter { get; set; }
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<OrderItem> OrderItem { get; set; }
    }
}
